export const userActionTypes = {
    SIGNIN_WITH_EMAIL_START: 'SIGNIN_WITH_EMAIL_START',
    SIGNIN_WITH_GOOGLE_START: 'SIGNIN_WITH_GOOGLE_START',
    SIGNIN_WITH_SUCCESS: 'SIGNIN_WITH_SUCCESS',
    SIGNIN_WITH_FAILURE: 'SIGNIN_WITH_FAILURE',
    SIGNUP_START: 'SIGNUP_START',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    USER_LOGOUT_START: 'USER_LOGOUT_START',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE'
}